### ISSUE TITLE
HPOVServerProfileTemplate Template copy / import

### ISSUE THREAD

**Issue by c0c00n** [HewlettPackard/POSH-HPEOneView#154] opened 2016-07-27 12:28 UTC
Hi Chris,

I tried to generate new HPOVServerProfileTemplate's for each of my server. Because on each profile i will use different Ethernet connections, so the alerting is all the time yellow when i use a global "Template" for all the servers.

Now i tried to export a kind of basic template and generate a new one trough the import. Looks like the import / copy in `New-HPOVServerProfileTemplate` is not implemented in that version.

Please can u give me some advise.

`Get-HPOVServerProfileTemplate -Name SourceTemplate -Export -location c:\myTemplates\` -works
`New-HPOVServerProfileTemplate -import -file c:\myTemplates\_ServerProfileTemplates.json` -failing

Thank you
Mike
### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version:  2.00.02-0219211
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 4.0
Name  : WSManStackVersion
Value : 3.0
Name  : SerializationVersion
Value : 1.1.0.1
Name  : CLRVersion
Value : 4.0.30319.42000
Name  : BuildVersion
Value : 6.3.9600.17400
Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}
Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment] 2016-07-28 16:53
Server Profile Templates are meant for compute nodes that share the same configuration.  If you are not looking to compliance, or using the Template to dictate the ongoing policy for a Server Profile, use the `Copy-HPOVServerProfile` Cmdlet to achieve what you are trying to do.

Import on all Cmdlets that support that parameter do work, as long as the object to import is, and the properties that are within the object are unique.  What they do not do right now is remove attributes that are unique for the source only.

As a workaround, you could take a Server Profile that you have configured what you want, then use the `ConvertTo-HPOVServerProfileTemplate` Cmdlet to create your template.

**Comment by CermakPOI** [comment] 2016-10-19 11:28
Why do i have an Export when i cannot import it?
I would need the import function to clone the Config to a Test-Oneview appliance.

**Comment by ChrisLynchHPE** [comment] 2016-10-19 15:53
If you want to clone resources to another appliance, I would suggest you look at the [Import/Export Resources](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Import-Export-OVResources) sample script that is posted on the [Wiki](https://github.com/HewlettPackard/POSH-HPOneView/wiki).

**Comment by CermakPOI** [comment] 2016-10-20 10:40
I imported almost everything else using these Scripts (with a few glitches since it's 1.20 based).
Funny: The script does **NOT** import Profile Templates. 
The question is still there: What can i do with an Export when there is no import function? Is there any other way to import the json file?

**Comment by mathewcubovic** [comment] 2021-02-22 18:51
Hi chris,
I exported JSON Template: `Get-HPOVServerProfileTemplate -Name SY_480_Teplate -Export -Location C:\install`
Converted from JSON and POST it like you mentioned and I get:

```powershell
Send-HPOVRequest : The JSON in the request is not valid. There is a problem on line 1 near column 2. Correct the invalid JSON and retry the request. 
At line:1 char:1
+ Send-HPOVRequest -uri /rest/server-profile-templates -body $SPTObject ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : INVALID_JSON_MAPPING,Send-HPOVRequest
```

Using HPOneView.500 module, PS ISE.
If I use Powershell Corre 7 the task completes with Error TaskState.
Thanks for your sugestions.
Mathew
    
[ServerProfileTemplates.zip](https://github.com/HewlettPackard/POSH-HPEOneView/files/6024417/ServerProfileTemplates.zip)

**Comment by ChrisLynchHPE** [comment] 2021-02-22 19:04
The issue is that the JSON itself contains extra content.  Remove the `[` on line 1, and the trailing `]` on line 169, and you can then perform the operation.  As I have done in the attached updated JSON file.

[ServerProfileTemplates_updated.zip](https://github.com/HewlettPackard/POSH-HPEOneView/files/6024531/ServerProfileTemplates_updated.zip)

**Comment by mathewcubovic** [comment] 2021-02-23 10:32
Hi Chris, thank you for your response, the extra brackets was the cause. The command now runs correctly, but unfortunately finish with TaskState Error. Maybe validation configuration fail? Are you sure, that mentioned rest api post is able to create whole ServerProfileTemplate from converted JSON? I suppose there are some info about it in appliance SupportDump. If yes could you please advice me which one in the .sdmp is the right one? Or any better troubleshoot method? Thanks for your hint. It would be perfect if there is an -import param in New-HPOVServerProfileTemplate, which would handle all this stuff. Thanks

**Comment by ChrisLynchHPE** [comment] 2021-02-23 18:43
You need to examine the `taskErrors` property of the returned task.  So, you should do the following:

```powershell
$Resp = Send-HPOVRequest -uri /rest/server-profile-templates -body (Get-Content C:\server-profile-template.json -raw) -Method POST | Wait-HPOVTaskComplete

if ($Resp.status -ne 'Completed') {
    $Resp.taskErrors | % {
        Write-Host "Message: " $_.message
        Write-Host "Recommended actions: " $_.recommendedActions
    }
}
````

**Comment by mathewcubovic** [comment] 2021-02-24 09:31
Great debug method Chris, 
I got this output:
Message:  The value specified for the server profile template serial number assignment type is not valid or not supported.
Recommended actions:  Specify a valid serial number assignment type.
I changed the "serialNumberType": "**UserDefined**" value to "**Virtual**", and after that also iLO required define password, which value was null. And now the POST works nice. Is that "**Virtual**" value for automated import ServerProfileTemplate correct? Great thanks.

**Comment by ChrisLynchHPE** [comment] 2021-02-24 17:13
If the `serialNumberType` or `macAddressType` are set to `UserDefined`, then you need to specify a value within the associated property.  For `macAddressType`, that would be within the `connections` property.

With what @c0c00n was trying to do, I would strongly suggest you use [ConvertTo-OVPowerShellScript](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.50/library/convertto-ovpowershellscript) here.  Exporting then importing is not very forgiving to modification if you are just trying to work with the JSON string object.  You could of course use `ConvertFrom-Json` to import the JSON string document into a PowerShell object.  But then you need to know the API details of the object.

**Comment by quinh** [comment] 2021-09-06 13:23
Hi @ChrisLynchHPE  - i've the same thing to accomplish like mathew, syncing templates from one oneview instance to more than one other and i am looking for a way to do this.

I did what you recommended here:

> You need to examine the `taskErrors` property of the returned task. So, you should do the following:
> 
> ```powershell
> $Resp = Send-HPOVRequest -uri /rest/server-profile-templates -body (Get-Content C:\server-profile-template.json -raw) -Method POST | Wait-HPOVTaskComplete
> 
> if ($Resp.status -ne 'Completed') {
>     $Resp.taskErrors | % {
>         Write-Host "Message: " $_.message
>         Write-Host "Recommended actions: " $_.recommendedActions
>     }
> }
> ```

and get:

```
Message:  Unable to determine the server hardware type /rest/server-hardware-types/F9C39CDB-100B-49D0-A6E5-B8678EA8B069.
Recommended actions:  Specify a valid server hardware type.
```

I've the same Server-hardware-type across all oneviews. Is there any other possibility to actually synchronize the templates or should customers modify their templates rather by `Remove-OVServerProfileTemplate` and a recreation by `New-OVServerProfileTemplate` with all settings coming from the script against each instance?

I assume that when I have the ServerProfileTemplates in place, and created some ServerProfiles out of this Template and then `Remove` the ServerProfileTemplates, that the  link between Profile and the Template is gone and my described method is complete nonsense.

**Comment by ChrisLynchHPE** [comment] 2021-09-08 16:31
Server profile templates and server profiles are the most complex resources within OneView.  They have many associations to other resources, and that is linked via resource uri's.  These addresses are unique per appliance.  The advice here is to instead of trying to export the resource object to JSON or PowerShell object format and attempt to "import" it to another appliance, use `ConvertTo-OVPowerShellScript`.  Especially for parent policy objects, like server profile templates.

Otherwise, you will need to programmatically need to process the source object and replace the uri's with valid ones from the target appliance.  For instance, the `serverHardwareTypeURI` attribute value would need to be identified on the target appliance and replaced. 

Example (which assumes the profile is for a non-BladeSystem or non-Synergy server):

```powershell
# Connect to appliance1, which will be the first connection made and thus default connection within $ConnectedSessions
$appliance1 = Connect-OVMgmt -Hostname appliance1 -Credential $MyCreds

# Connect to appliance2
$appliance2 = Connect-OVMgmt -Hostname appliance2 -Credential $MyCreds

# Get server profile resource from appliance1
$Prf1 = Get-OVServerProfile -Name Prf1

# Get the server hardware type name
$shtname = (Send-OVRequst -Uri $Prf1.serverHardwareTypeURI).name

# Get the server hardware type object from the target appliance2 appliance
$targetsht = Get-OVServerHardwareType -Name $shtname -ApplianceConnection $appliance2 -ErrorAction Stop

# Update the source profile object with the new URI
$Prf1.serverHardwareTypeURI = $targetsht.uri

# Remove attributes from the source profile that are not needed
$Prf1 | Select -Exclude uri, created, modified, eTag, status, state

# Create the profile object on the target appliance
Send-OVRequest -Uri /rest/server-profiles -Method POST -Body $Prf1 -Hostname $appliance2 | Wait-OVTaskComplete
```

Now, this example is very basic, and you may have to update other attributes as well.  But this should provide you with some of the necessary steps you would need to do at a minimum.

**Comment by quinh** [comment] 2021-09-09 11:53
@ChrisLynchHPE  - Thank you so much for your effort, I really appreciate your enthusiasm here to help user/customers.

As you suggested I've looked into the `ConvertTo-OVPowerShellScript` resource. I've dumped my test  into a .ps1 file and scanned through the lines to understand what this conversion is about.  Somewhere in this script you find the lines

```
# -------------- Attributes for advanced settings
New-OVServerProfileTemplate -Name $name -ServerProfileDescription $spdescription  -ServerHardwareType $sht -EnclosureGroup $eg [...]
```

So, I've 4 different Oneviews (Synergys) and my intention is to synchronize SPTs. Even if I would manipulate the converted script with existing URIs from that oneview instance, I would need to remove the synced template on appliance 2, so that the next iteration of updates (synchronization) could deliver the updates via create (running `New-OVServerTemplate` against appliance2 with an existing Name will probably fail).

I would not have a problem with that, but since a Server Hardware needs a Server Profile, which has a SPT as parent with a ID, this Profile would then get orphaned, because I've killed his parent. Maybe I would need to remove the Server Profiles from the hardware before I "synchronize", so that the new SPTs bring new SP but I am not sure if this would be kind of a drawback in terms of "do this operation on a production server w/o no maintenance window" (losing san/lan uplinks and so on).

More examples to be clear what i want to do:

iteration 1)
- instead of creating a new SPT in appliance2, i want to create "the same SPT as in appliance1" via an automated way

iteration 2)
- we want to update certain bios options in certain SPTs across all oneviews 

iteration 3)
- we want to add more network connections in certain SPTS across all oneviews


What would be the most elegant way to keep SPTs for multiple oneviews (synergy) in sync, w/o having to end up clicking the same attributes into multiple oneview guis and make sure to never misclick one of them (assuming we've the same hardware types in all of these instances)

I guess the answer is your Example with the programmatically update process.

PS: Shouldn't your Example be 
```
Send-OVRequest -Hostname appliance2 -Uri /rest/server-profiles -Method POST -Body $Prf1 | Wait-OVTaskComplete
```
So that the updaets $prf1 with the $targetsht.uri from appliance2 would end up on appliance2? :)

**Comment by ChrisLynchHPE** [comment] 2021-09-09 15:37
My point wasn't for you to really look at the source code for the Cmdlet I referenced.  It does not help you here with the example I provided above about updating uri references in resource objects.  Instead, using it to create your resource objects on appliances where they don't exist.  Then, you really should develop a script that updates those resources across the appliances you have.  Deleting and then recreating them would cause too much havoc for anyone's environment in my opinion.

As for the `Send-OVRequest` example, yes, I updated that to correct the mistake.

**Comment by DungKHoang** [comment] 2021-09-09 16:37
@quinh - If I understand your iterations, you want to update some settings in SPT (BIOS, network connections, other....to ensure that SPTs in appliance 2 are 'compliant' with SPTs in Appliance 1
So to update SPTs by adding new values to existing settings ( iteration 2) and 3) ), the process would be:
1 - Get the SPT 
2 - Locate the endpoint for the settings 
3- Add new values to existing attributes
4 - Save SPT with updated body
You can leverages those samples here for guidance: https://github.com/HewlettPackard/oneview-powershell-samples/blob/master/Server%20Profiles/Update-ProfileTemplateVolumeAttachTargets.ps1

https://github.com/HewlettPackard/oneview-powershell-samples/blob/master/Server%20Profiles/Update-LocaliLOAdminCredentials.ps1

For iteration 1), I'd suggest to 'export' all settings of SPT in Appliance 1 and of SPT in Appliance 2, do a comparison , then update SPT in App 2 if needed using the method described above
You can leverage the script here: https://github.com/DungKHoang/Import-Export-OneView-Resources
to export everything to Excel file for ease of reading.

Hope that helps
/HKD

**Comment by ChrisLynchHPE** [comment] 2022-07-19 19:05
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed by ChrisLynchHPE** 2022-07-19 19:05 UTC
Labels: Enhancement, Server Profiles, Server Profile Templates
